spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/argos?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: gmlwns12!

  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

jwt:
  secret-key: FF41EE656A53DAADFCEC092EA8A2157A6E00F3B5562F1D2204941A10F0CABECEF72B8AB79648B0FE3465FA7ED533BCB52CA3F7A733A56D353D8A5910DC8B5C53
  token-period-seconds: 864000
  refresh-token-period-seconds: 864000

#file-api:
#  url: http://bluesignal.iptime.org:35004

#kafka:
#  server: "3.37.215.231:29092"

logging:
  level:
    root: info

